import Head from "next/head";
import { Intro } from "../components/Intro";
import { Work } from "../components/Work";

import { stfu } from "../utils/apps/stfu";
import { qi } from "../utils/apps/qi";

export default function Home() {
  return (
    <div className="w-full h-full bg-white scroll-smooth">
      <Head>
        <title>Cauã Adomaitis</title>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#fff" />
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <Work app={stfu} />
      <Work app={qi} />
    </div>
  );
}
